import Header from "@/shared/Header";
import "./globals.css";
import { Raleway, Merriweather_Sans } from "@next/font/google";
import Footer from "@/shared/Footer";

const raleway = Raleway({
  variable: "--display-font",
});

const merriweather = Merriweather_Sans({
  variable: "--body-font",
});
export const metadata = {
  icons: { icon: "/favicon.png" },
  title: "Panaverse Dao Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className={`${raleway.variable} ${merriweather.variable}`}>
      <body className=' bg-[#F2F2F2]'>
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
